### ISSUE TITLE
Cross-domain AJAX example no longer works

### ISSUE THREAD

**Issue by HallofFamer** [ajaxboy/cjax#25]
It shows this message when clicking on the cross-domain AJAX link:

> 301 Moved Permanently
> The resource has been moved to https://sourceforge.net/; you should be redirected automatically. 

Not sure if it is for me only or it does not work for anyone at all:
http://cjax.sourceforge.net/examples/cross_domain_ajax.php

**Comment by ajaxboy** [comment]
I guess it still works, what doesnt work is the url it is going to, (google projects) which closed down.
