### ISSUE TITLE
Turn examples into HTML5

### ISSUE THREAD

**Issue by ajaxboy** [ajaxboy/cjax#29]
Not a huge priority but would be nice to turn the examples in examples directory into HTML5

**Comment by HallofFamer** [comment]
Actually I plan to use bootstrap for these examples for CJAX 6.0, not sure if you agree with this but I think its a better idea.

**Comment by ajaxboy** [comment]
Bootstrap is fine. But the change above is for 5.9,  we will keep 5.8 , 5.9  available when we release 6.0. The first release for 6.0 will be  RC's,  that is standard procedure in major all  releases. Eg. When 5.0 was released,  there were at least 3 or 4 RC's. And the first one was beta, it has to be exposed to the public for some time until we can pick any bug reports of good feel of how stable it is on the scale.

**Comment by ajaxboy** [comment]
This was mostly completed.
