### ISSUE TITLE
overlay not working in cjax-5.9rc3b

### ISSUE THREAD

**Issue by oniwo** [ajaxboy/cjax#34]
The overlay API is not working for me. When I try the overlay, I get the error message 
"Error: File not found filename/param1/param2"

But the same arguments/parameters work perfectly when I pass them to the location API.

Overlay had had been working for me with the same code in CJAX-5.8
PS: Am using cjax with CodeIgniter 3.x

**Comment by ajaxboy** [comment]
Must be cause of the current working directory.
The location function doesn't use the ajax.php file as a dispatcher,  while the overlay function does.
 
I assume you can resolve this by changing the url, for example right now is, 'ajax.php?controller/function/    try   '../ajax.php?controller/function', etc.

Try to figure out where the url is going to.

**Comment by ajaxboy** [comment]
Does the console tell you what URL is it looking for?

Please keep reporting any issues you find, so that they can be corrected and be included in near future releases,
I

**Comment by ajaxboy** [comment]
Also,  the newest latest release is  5.9 RC 4

**Comment by ajaxboy** [comment]
Can you show the code you are using, and path to the file you calling it from?

**Comment by oniwo** [comment]
I am still unable to solve this overlay problem.
   ~ am hiding the 'ajax.php' from the url.
   ~ I have tried using absolute path; does not work also.

**Comment by ajaxboy** [comment]
path and code - can you post the code you are using to call the overlay, and how relative are you from  cjax directory or how far?

**Comment by ajaxboy** [comment]
I have a fix for the overlay() function, will push it to repo soon.

**Comment by oniwo** [comment]
How hard is it to fix this one?

"ERROR - 2017-02-17 08:20:26 --> Severity: 8192 --> Methods with the same name as their class will not be constructors in a future version of PHP; ajax has a deprecated constructor /var/www/html/testingcjax/cjax/ajax.php 40"

If possible fix this one too before, and push both fixes. Thanks so much for your time and effort.

**Comment by ajaxboy** [comment]
What is your version of php?  it's a matter of being able to reproduce the issue, then it can be fixed

**Comment by ajaxboy** [comment]
The changes are in place, you may now download the latest and the overlays should be working.  As far as the other issue, i will need more information.  Open a new issue# ticket and provide as much details as possible.
