### ISSUE TITLE
Manipulating Properties not working in cjax-5.9-RC4

### ISSUE THREAD

**Issue by oniwo** [ajaxboy/cjax#35]
Property manipulation not working for me.
$ajax->optionList = array('selectedIndex'=>-1);
does not deselect the list. The first item in the list remains selected.

**Comment by HallofFamer** [comment]
Does this not work for you on CJAX 5.9 RC4 specifically, or it doesnt work on other versions either? To my understanding, CJAX's property manipulation API cannot modify certain properties, such as 'class'.

**Comment by ajaxboy** [comment]
Thanks for reporting, 

this seems like an option that should work.

Will add support to any of these options that don't work. Please let me know if you find anymore.

**Comment by ajaxboy** [comment]
Just tried it, and it seemed to work:

I used this example to test on:
http://cjax.sourceforge.net/examples/propagate_dropdown.php


On controller,  method: propagate(),  at the bottom after: $ajax->select('dropdown2',$data);

Added: 
...... after: $ajax->select('dropdown2',$data);

		$ajax->dropdown2 =  array('selectedIndex'=> 3);
		
		$ajax->wait(3);

		$ajax->dropdown2 =  array('selectedIndex'=> 1);
		
		$ajax->wait(3);

		$ajax->dropdown2 =  array('selectedIndex'=> -1);

The test passed, and it worked.

Please let me know the conditions you tested on, as this seems to be working.

**Comment by ajaxboy** [comment]
RC 5 is already out: https://github.com/ajaxboy/cjax/releases/tag/5.9RC5
Let me know if you find any issues.

**Comment by ajaxboy** [comment]
Are you able to replicate this issue still ?

**Comment by oniwo** [comment]
No, the issue is gone. Thanks.
