### ISSUE TITLE
Godaddy Cjax not responding

### ISSUE THREAD

**Issue by Bobin56** [ajaxboy/cjax#5]
i used this plugin to pull a simple ajax request to update my notification table.i was testing my application on justhost.com and local host and it worked just fine but when i launch it and move to godaddy it does not work ,please help me as of possible causes of this.i just use it just once in this line of code.

 $(document).ready(function(){		  
     $('#achor1').click(function(){
     $.get('ajax.php?test/test/Hello', function(response) {
           })
       });
});

**Comment by ajaxboy** [comment]
I am closing this issue, since there has been no response for a long time. For further debug info, please read this document: http://cjax.sourceforge.net/examples/docs/debugging.php
