### ISSUE TITLE
Refused to set unsafe header "Content-length" Refused to set unsafe header "Connection"

### ISSUE THREAD

**Issue by frecervantes** [ajaxboy/cjax#54]
why I'm getting this.  in localhost while testing cjax.

some google expalnation:
XMLHttpRequest isn't allowed to set these headers, they are being set automatically by the browser.

am I doing something wrong?

**Comment by ajaxboy** [comment]
@frecervantes 
What version of PHP are you using?
Are you using any framework, or anything else?
Are you using Jquery or any other Js Framework?

**Comment by frecervantes** [comment]
thanks ajaxboy, allready fixed.

**Comment by frecervantes** [comment]
Hello Ajaxboy, I'm testing locally the Cjax's functionality and everything
is ok.
It's an awesome framework, though, for people like me, who don't master the
javascript language, would be very useful if you *go further* and create
some sets of utilities, plugins, ect. to do simple, necessary and useful
things like:

   - *Geolocation *(using in the background leafled.js or any open source
   library). Draw maps, routes, ect.
   - *FCM *(FireBase Cloud Messaging) may be using webPush codelab
   - *Local Storage*.

using your simple *calls  *to do it. This will boost the cjax framework,
especially with the beginners.
there may be a *plugin for every single feature *you want to add to the
framework.

Just an idea.

Regards.
